"""Generate a rubric-aligned PPTX, using actual experiment results when available."""
import argparse
import json
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

ROOT = Path(__file__).resolve().parents[1]
MEMBERS = [
    ("Member 1", "FILL PRIVATELY"),
    ("Member 2", "FILL PRIVATELY"),
    ("Member 3", "FILL PRIVATELY"),
    ("Member 4", "FILL PRIVATELY"),
]


def build(group, video_link, run, evaluation, output):
    prs = Presentation()
    prs.slide_width, prs.slide_height = Inches(13.333), Inches(7.5)
    navy, white, mint = RGBColor(18, 29, 49), RGBColor(240, 244, 250), RGBColor(97, 222, 190)

    def textbox(slide, text, left, top, width, height, size=24, color=white):
        box = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tf = box.text_frame
        tf.word_wrap = True
        for i, line in enumerate(text.split("\n")):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.text = line
            p.font.name = "Aptos"
            p.font.size = Pt(size)
            p.font.color.rgb = color
            p.space_after = Pt(12)
        return box

    def slide(title, body, note, image=None, source="Our implementation / supplied assignment brief"):
        s = prs.slides.add_slide(prs.slide_layouts[6])
        s.background.fill.solid()
        s.background.fill.fore_color.rgb = navy
        textbox(s, title, .65, .45, 12, 1, 32, mint)
        if image and image.exists():
            textbox(s, body, .65, 1.6, 5.4, 4.9, 22)
            s.shapes.add_picture(str(image), Inches(6.35), Inches(1.9), width=Inches(6.2))
        else:
            textbox(s, body, .65, 1.6, 12, 4.9, 24)
        textbox(s, f"{len(prs.slides):02d}   |   {source}", .65, 7, 12, .35, 11)
        s.notes_slide.notes_text_frame.text = note
        return s

    slide("Playing Atari with Deep Reinforcement Learning",
          f"DRL Assignment Problem II • Group {group}\n" +
          "\n".join(f"{name} — {bits}" for name, bits in MEMBERS) +
          "\nEducational DQN demonstration + paper analysis",
          "0:00–0:25. Introduce the group and assigned paper. Verify group number and names.")
    slide("Why learn directly from game screens?",
          "Objective: learn useful actions from pixels and reward.\n"
          "Challenge: rewards can be delayed; consecutive observations are correlated.\n"
          "Motivation: avoid hand-designed features for every game.",
          "0:25–1:00. Explain why raw images make a Q-table impractical. Describe the motivation.",
          source="Mnih et al. (2013), sections 1–2")
    slide("Our input and network",
          "Grayscale → 84×84 → stack four recent frames.\n"
          "Conv: 16 filters → Conv: 32 filters → 256-unit hidden layer.\n"
          "Output: one unrestricted Q-value per action.\n"
          "One frame hides motion; multiple frames provide movement cues.",
          "1:00–1:35. Show src/dqn.py and explain the four-frame input. Our wrapper resizes directly; "
          "the assigned paper used a resize/crop sequence.", image=ROOT / "screenshots/frame_stack.png",
          source="Our code; architecture checked against paper section 4.1")
    slide("How the agent learns",
          "Explore with epsilon-greedy actions.\n"
          "Store (state, action, reward, next state, terminal) in replay.\n"
          "Sample experiences uniformly; reuse older interactions.\n"
          "Fit Q(state, chosen action) to a detached TD target.\n"
          "Same network supplies next-state values; no periodic target copy.",
          "1:35–2:15. Show replay buffer and agent.py. Explain why random sampling is useful.")
    slide("Connect the equation to the code",
          "y = r                         if terminal\n"
          "y = r + gamma × max Q(s′, a′)  otherwise\n"
          "Loss = mean[(Q(s, a) − y)²]\n"
          "Example: r=1, gamma=0.99, max next Q=5 → y=5.95.\n"
          "If Q(s,a)=4.2: TD error=1.75; squared error=3.0625.",
          "2:15–2:50. Point to gather(), no_grad(), backward() and optimizer.step(). The target is "
          "fixed during this update, even though next-state values come from the same network.")
    slide("Published results — not our scores",
          "Table 1: DQN / human\n"
          "Beam Rider: 4092 / 7456    Breakout: 168 / 31\n"
          "Enduro: 470 / 368          Pong: 20 / −3\n"
          "Q*bert: 1952 / 18900       Seaquest: 1705 / 28010\n"
          "Space Invaders: 581 / 3690\n"
          "Above human on three games; substantial gaps remain elsewhere.",
          "2:50–3:30. These are published scores, not generated by our repository. Table 1's DQN "
          "average and DQN Best are different rows; use the average row shown here.",
          source="Mnih et al. (2013), Table 1, section 5.3")
    slide("Our experiment protocol",
          "Breakout only; reduced budget specified in config/breakout.json.\n"
          "Replay 5,000; batch 32; gamma 0.99; RMSprop; MSE.\n"
          "Clip training rewards; report original game scores.\n"
          "Evaluate random and trained policies on matching seeds.\n"
          "Record versions, checkpoint, CSV logs and gameplay.",
          "3:30–4:05. State actual training budget and hardware after running. Show config, command "
          "and summary.json. Explain direct resize and FIRE helper as documented deviations.")
    summary = evaluation / "summary.json"
    training_summary = run / "summary.json"
    if summary.exists():
        data = json.loads(summary.read_text())
        body = "\n".join(f"{label}: mean={data[label]['mean']:.2f}; "
                         f"sample SD={data[label]['std']}; n={data[label]['episodes']}"
                         for label in ("random", "trained"))
        body += "\nCompare evaluated scores, not TD loss alone.\nSmall sample; no full benchmark reproduction claim."
        if data["trained"]["mean"] <= data["random"]["mean"]:
            body += "\nThis run did not demonstrate improvement over random play."
        else:
            body += "\nHigher observed mean; more training seeds needed to assess reliability."
    else:
        body = "PENDING: run training and evaluation.\nNo scores have been invented.\n"
        body += "Show original score curves, evaluation mean/SD and gameplay.\n"
        body += "If performance does not improve, report that observation honestly."
    if training_summary.exists():
        data = json.loads(training_summary.read_text())
        body += f"\nCompleted steps: {data['completed_steps']}; updates: {data['updates']}."
    slide("Our observed results", body,
          "4:05–4:50. Replace pending material by rerunning the generator after experiments. "
          "Interpret the observed difference and its uncertainty. Play a short gameplay clip.",
          image=evaluation / "comparison.png")
    slide("Limitations, future scope and conclusion",
          "Limitations: short run, one game, small replay and modern preprocessing.\n"
          "Sparse feedback and long-horizon decisions remain difficult.\n"
          "Future experiment: longer budgets, multiple training seeds and replay ablation.\n"
          "Later extensions: target network / Double DQN, clearly labelled separately.\n"
          "Conclusion: demonstrate the complete learning pipeline; assess actual policy scores.",
          "4:50–5:25. Separate our experiment limitations from those discussed in the research paper.")
    slide("Proof of each contributor's work",
          "Member 1: PENDING actual work + evidence\n"
          "Member 2: PENDING actual work + evidence\n"
          "Member 3: PENDING actual work + evidence\n"
          "Member 4: PENDING actual work + evidence\n"
          "Show named commits, screenshots, run logs and speaking contributions.",
          "5:25–6:05. Replace these placeholders with actual equal contributions. Each person "
          "should show their own work while presenting their segment. Do not claim generated work "
          "as proof of an individual's contribution.")
    slide("References and recording",
          "Paper: https://arxiv.org/abs/1312.5602\n"
          "ALE: https://ale.farama.org/getting-started/\n"
          "Gymnasium: https://gymnasium.farama.org/\n"
          "Repository: https://github.com/Eahmed99/aiml-drl-atari/tree/replay_buffer_branch\n"
          f"Google Drive recording: {video_link}",
          "6:05–6:25. Verify recording link permissions. Final duration must stay under seven minutes.")
    output.parent.mkdir(parents=True, exist_ok=True)
    prs.save(output)
    print(f"Saved {output}; {output.stat().st_size / 1e6:.2f} MB")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--group", default="PENDING")
    p.add_argument("--video-link", default="PENDING — insert accessible Drive link")
    p.add_argument("--run", type=Path, default=ROOT / "results/breakout")
    p.add_argument("--evaluation", type=Path, default=ROOT / "results/evaluation")
    p.add_argument("--out", type=Path)
    args = p.parse_args()
    output = args.out or ROOT / f"submission/DRL_PlayingAtari_Group{args.group}.pptx"
    build(args.group, args.video_link, args.run, args.evaluation, output)
